WORKER_CONNECTION_ESTABLISH = 'WORKER_CONNECTION_ESTABLISH'
MASTER_CONNECTION_ESTABLISHED_ACK = 'MASTER_CONNECTION_ESTABLISHED_ACK'

MASTER_CREATE_TASK = 'MASTER_CREATE_TASK'
WORKER_CREATE_TASK_ACK = 'WORKER_CREATE_TASK_ACK'

WORKER_TASK_DONE = 'WORKER_TASK_DONE'
MASTER_TASK_DONE_ACK = 'MASTER_TASK_DONE_ACK'

