# Key definition
CMD = 'cmd'
DATA = 'data'

# CMD
# Main establish connection
MAIN_CONNECTION_ESTABLISHED = 'MAIN_CONNECTION_ESTABLISHED'
WORKER_CONNECTION_ESTABLISHED_ACK = 'WORKER_CONNECTION_ESTABLISHED_ACK'


# Main sent task to worker
MAIN_TASK = 'MAIN_TASK'
WORKER_TASK_ACK = 'MAIN_TASK_ACK'
WORKER_TASK_DONE = 'MAIN_TASK_DONE'

