# Key definition
CMD = 'cmd'
DATA = 'data'

# CMD
# Main establish connection
MASTER_CONNECTION_ESTABLISHED = 'MASTER_CONNECTION_ESTABLISHED'
WORKER_CONNECTION_ESTABLISHED_ACK = 'WORKER_CONNECTION_ESTABLISHED_ACK'


# Main sent task to worker
MASTER_CREATE_TASK = 'MASTER_CREATE_TASK'
WORKER_CREATE_TASK_ACK = 'WORKER_CREATE_TASK_ACK'
WORKER_TASK_DONE = 'WORKER_TASK_DONE'

